version: '3'

volumes:
  pg_data:
  static:
  static_frontend:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ../backend/
    env_file: .env
    volumes:
      - static:/app/static_django/
      - media:/app/media/
    depends_on:
      - db
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - static_frontend:/app/result_build/
  nginx:
    build: ../nginx/
    env_file: .env
    ports:
      - 8080:80
      #- 80:80
    volumes:
      - static:/static_django/
      - media:/media/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_frontend:/static_frontend/
    depends_on:
      - backend
