version: '3'

volumes:
  pg_data:
  static:
  static_frontend:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ../backend/
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - static_frontend:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      # - 8000:80
      - 80:80
    volumes:
      - static:static/
      - media:/media/
      - static_frontend:/static_frontend/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - db
